stages:
  - test

playwright-tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.44.0-jammy
  script:
    - npm ci
    - npx playwright install --with-deps
    - npx playwright test
  artifacts:
    when: always
    reports:
      junit: report.xml
    paths:
      - playwright-report

# image → Uses the official Playwright Docker image (so no setup headache).
#npm ci → Installs dependencies from your package-lock.json.
#npx playwright install --with-deps → Ensures all browsers are installed.
#npx playwright test --reporter=html,junit → Runs tests and generates:
#HTML report → inside playwright-report folder
#JUnit XML report → inside playwright-report/results.xml
#Artifacts → GitLab will keep reports after the job finishes (you can download them from the UI).